Repository sympa-community/sympa-ansible, pull requests merged in 2019-03, with the labels that each got.

#52 Remove useless Postfix monitoring task.
  roles/postfix/tasks/main.yml
Labels: refactoring

#51 Remove duplicate apt task from Postfix role.
  roles/postfix/tasks/main.yml
Labels: refactoring

#50 Remove roles_path from ansible configuration
  ansible.cfg
Labels: refactoring

#49 Use systemd module for Sympa startup.
  roles/sympa/tasks/sympa_startup.yml
Labels: refactoring

#48 Remove datasources tool.
  roles/sympa/files/tools/datasources
  roles/sympa/tasks/main.yml
  roles/sympa/tasks/sympa_tools.yml
Labels: refactoring

#47 Remove unrelated server types from virtual hosts.
  roles/apache/tasks/main.yml
  roles/postfix/tasks/main.yml
Labels: refactoring

#44 Fix environement typo.
  environments/template/tasks/common.yml
Labels: refactoring

#42 Fix deprecated usage of with_items in apt task.
  roles/apache/tasks/main.yml
  roles/common/tasks/main.yml
  roles/postfix/tasks/main.yml
  roles/sympa/tasks/sympa_db_mysql.yml
  roles/sympa/tasks/sympa_prereq.yml
  roles/sympa/tasks/sympa_web.yml
Labels: deprecated

#56 Updated apache 2.4 config
  roles/apache/tasks/main.yml
  roles/sympa/tasks/main.yml
  roles/sympa/tasks/sympa_install/deploy.yml
  roles/sympa/tasks/sympa_install/get_sources_from_repo.yml
  roles/sympa/tasks/sympa_mail.yml
  roles/sympa/tasks/sympa_startup.yml
  roles/sympa/tasks/sympa_web.yml
  roles/sympa/templates/apache/sympa_web.conf.j2
  roles/sympa/templates/fcgi/sympasoap.service.j2
  roles/sympa/templates/fcgi/wwsympa.service.j2
Labels: bug

#63 Fix selection of database type
  roles/sympa/tasks/main.yml
Labels: bug, refactoring
